### PR TITLE
Add xamarin android support

### PR DESCRIPTION
**Pull request by annymsMthd**

### CODE REVIEW

**Review by thzinc — COMMENTED** [review]
How does the Proton build do with these updates? Proton has some specific references to Mono 5.0.1 cross-compilation libraries.

**Comment by annymsMthd** [comment]
I have the versions tagged on docker hub now. We can target the specific version with Proton.

**Review by thzinc — COMMENTED** [review]
How do other Docker image maintainers handle Dockerfiles with different tags? Should we have separate Dockerfiles for each tag?

**Comment by annymsMthd** [comment]
Negative. We just version stuff up like we would any other project. No need to make this too complicated

**Pull request merged**
